### ISSUE TITLE
make dockpulp more ressillient to pulp errors

### ISSUE THREAD

**Issue by TomasTomecek** [release-engineering/dockpulp#19]
```
2015-07-31 07:25:21,039 - atomic_reactor.plugin - DEBUG - Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/atomic_reactor-1.3.7-py2.7.egg/atomic_reactor/plugin.py", line 180, in run
    plugin_response = plugin_instance.run()
  File "/usr/lib/python2.7/site-packages/atomic_reactor-1.3.7-py2.7.egg/atomic_reactor/plugins/post_push_to_pulp.py", line 210, in run
    crane_repos = self.push_tar(image_stream, image_names)
  File "/usr/lib/python2.7/site-packages/atomic_reactor-1.3.7-py2.7.egg/atomic_reactor/plugins/post_push_to_pulp.py", line 199, in push_tar
    return uploader.push_tarball_to_pulp(image_names)
  File "/usr/lib/python2.7/site-packages/atomic_reactor-1.3.7-py2.7.egg/atomic_reactor/plugins/post_push_to_pulp.py", line 115, in push_tarball_to_pulp
    task_ids = p.push_tar_to_pulp(repos_tags_mapping, self.filename)
  File "build/bdist.linux-x86_64/egg/dockpulp/__init__.py", line 630, in push_tar_to_pulp
    self.upload(tarfile)
  File "build/bdist.linux-x86_64/egg/dockpulp/__init__.py", line 753, in upload
    data=data)
  File "build/bdist.linux-x86_64/egg/dockpulp/__init__.py", line 217, in _put
    return self._request('put', api, **kwargs)
  File "build/bdist.linux-x86_64/egg/dockpulp/__init__.py", line 88, in __call__
    answer = c(url, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests-2.7.0-py2.7.egg/requests/api.py", line 122, in put
    return request('put', url, data=data, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests-2.7.0-py2.7.egg/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests-2.7.0-py2.7.egg/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests-2.7.0-py2.7.egg/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests-2.7.0-py2.7.egg/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', error(111, 'Connection refused'))
```

This looks like a hiccup.

Do you think it would make sense to retry several times?

**Comment by Zyzyx** [comment]
Do you know the command that was being run? I'm usually reluctant to add blank-retry statements since they often delay showing a real error.

**Comment by TomasTomecek** [comment]
The real issue was that httpd was being restarted. So a couple seconds of downtime failed the whole build. Not sure if this is fine or not - one failed http request is able to fail the whole. But since builds are not that expensive, I guess it's fine. Feel free to close.

**Comment by breillyrh** [comment]
Issue was resolved in this commit: https://github.com/release-engineering/dockpulp/commit/cb1006fb71e3c76813f9c96decef4801a59b6c7c
