### ISSUE TITLE
Fails to upload output from docker-1.10

### ISSUE THREAD

**Issue by twaugh** [release-engineering/dockpulp#34]
With docker-1.10's `docker save` output, dock-pulp.py fails to upload the tarball.

```
dock-pulp.py -s qa upload /var/tmp/hello-world-1.10.tar.gz redhat-twaugh-test
INFO      uploading /var/tmp/hello-world-1.10.tar.gz
INFO      Ensuring image conforms to Pulp requirements
INFO      Layers in this tarball:
INFO        768d4f50f65f00831244703e57f64134771289e3de919a576441c9140e037ea2
INFO        32b858239cf8ee08d09055fbee0c3f1ecf082d8cbd3ab5fc4d8855238fa22a21
Traceback (most recent call last):
  File "/usr/bin/dock-pulp.py", line 678, in <module>
    main()
  File "/usr/bin/dock-pulp.py", line 58, in main
    cmd(opts, args[1:])
  File "/usr/bin/dock-pulp.py", line 633, in do_upload
    vers = dockpulp.imgutils.get_versions(metadata)
  File "/usr/lib/python2.7/site-packages/dockpulp/imgutils.py", line 75, in get_versions
    vers[image_id] = data['docker_version']
KeyError: 'docker_version'
```

**Comment by breillyrh** [comment]
Issue resolved by [commit](https://github.com/release-engineering/dockpulp/commit/a1dae3755e4ff03e7cfb121479c8293af66331c1).
