### ISSUE TITLE
createRepo API changed

### ISSUE THREAD

**Issue by twaugh** [release-engineering/dockpulp#46]
The createRepo() API changed in a35f20591091b11470ce5731d7b0e42bb4b1c752, breaking dock-pulp-bootstrap and every client wanting to create repositories.

```
Traceback (most recent call last):
  File "/usr/bin/dock-pulp-bootstrap.py", line 4, in <module>
    __import__('pkg_resources').run_script('dockpulp==1.14', 'dock-pulp-bootstrap.py')
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 735, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1659, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/lib/python2.7/site-packages/dockpulp-1.14-py2.7.egg/EGG-INFO/scripts/dock-pulp-bootstrap.py", line 52, in <module>
    
  File "/usr/lib/python2.7/site-packages/dockpulp-1.14-py2.7.egg/EGG-INFO/scripts/dock-pulp-bootstrap.py", line 43, in create_everything
    
  File "build/bdist.linux-x86_64/egg/dockpulp/__init__.py", line 365, in createRepo
TypeError: 'str' object does not support item assignment
```

**Comment by breillyrh** [comment]
Fixed bug in this commit https://github.com/release-engineering/dockpulp/commit/c19344c0336677003a4ff7d13ce06607f39d39fb
